# name: Build and Deploy

# This workflow is triggered on a push to the main branch
# on:
#   push:
#     branches:
#       - main

# jobs:
#   # Define the build job
#   build:
#     # Specify the runner environment
#     runs-on: ubuntu-latest

#     steps:
#     # Step 1: Checkout the code from the repository
#     - name: Checkout Code
#       uses: actions/checkout@v2

#     # Step 2: Log in to Azure using credentials stored in GitHub secrets
#     - name: Log in to Azure
#       uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}

#     # Step 3: Build and push the Docker image to a container registry
#     - name: Build Docker Image
#       run: |
#         docker build -t idata2502-portfolio-web:latest .
#         docker push birgilv/idata2502-portfolio-web:latest

#     # Step 4: Scan the Docker image for vulnerabilities using Grype
#     - name: Scan Docker Image
#       run: |
#         grype birgilv/idata2502-portfolio-web:latest --fail-on high

#     # Step 5: Deploy the application to Azure Kubernetes Service (AKS)
#     - name: Deploy to AKS
#       run: |
#         kubectl apply -f aks-quickstart.yml
