name: Tests

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  rspec_and_rubocop:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.8'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: bundle install
      
      # Step 4: Set executable permissions
      - name: Set Executable Permissions
        run: chmod +x bin/rails

      # Step 5: Set up database
      - name: Set Up Database
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:seed

      # Step 6: Run Tests
      - name: Run Rails Tests
        run: bin/rails test

      # Step 7: Run RuboCop linter
      - name: Run RuboCop with Autocorrect
        run: bundle exec rubocop -A