name: Linting

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0' # Adjust to match your project's Ruby version
          bundler-cache: true

      - name: Install Dependencies
        run: |
          bundle config set deployment 'false'
          bundle install --jobs 4 --retry 3

      - name: Run RuboCop
        run: bundle exec rubocop --rails

      - name: Debug Ruby Environment
        run: |
          ruby --version
          bundle --version
          bundle list